### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by duxiangcheng** [ZeroAct/SceneTextRemover-pytorch#4]
hey, could you provide some background images and text binary images?

**Comment by ZeroAct** [comment]
I can't help you with that because of the copyright...

You can use any images whatever you want for background images.
And you can create text binary images following [this](https://stackoverflow.com/questions/24085996/how-i-can-load-a-font-file-with-pil-imagefont-truetype-without-specifying-the-ab).

Thank you!
